### PR TITLE
Fix the 'Fix rubocop warnings'

### PR DESCRIPTION
**Pull request by mburns**
yo dawg.

This is a sort-of rebase of/connected to #30

The difference is that I used the default `.rubocop.yml` as the rules file path, not `.rubocop_todo.yml`, so running `rubocop` without any flags completes successfully. The rules can be tuned as it makes sense.

### CODE REVIEW

**Comment by mburns** [comment]
@filler ping :)

**Comment by filler** [comment]
Sorry, been head down on other stuff.  



:+1: lgtm.  Rebase and itll get merged.

**Comment by mburns** [comment]
@filler, thanks! I've rebased. :smile:

**Comment by filler** [comment]
@mburns ugh, once more kind sir? A fix version went out for the Designate team.

And thanks for your contributions!  If youre ever in AUS2, come find us.  :smile:

**Comment by filler** [comment]
@mburns++ for being awesome

**Pull request merged**
