### PR TITLE
Update filter templates, system model, container, and logging for 7x …

### PR DESCRIPTION
**Pull request by dimtruck**
…release

This is required so that we can release version 7.2.1.0 for repose with this cookbook.

### CODE REVIEW

**Comment by jamesyli** [comment]
I tested this branch for the need of DNS team. We also need to have `keystone-v2` and `url-extractor-to-header`. Other than that, it works great!

**Comment by jamesyli** [comment]
@dimtruck DO you need any help on this? I am seeing the branch needs to be rebased as well.

**Comment by dimtruck** [comment]
@jamesyli I haven't touched it yet.  I'm going to try to get to it this afternoon and will update once everything is gravy.

**Comment by dimtruck** [comment]
@jamesyli, @filler  please review this rebase so we can merge it.

**Comment by jamesyli** [comment]
Thanks! I saw you added support for `url-extractor-to-header` in https://github.com/rackerlabs/cookbook-repose/pull/45

**Comment by jamesyli** [comment]
As I mentioned earlier, any plan to add `keystone-v2` as well? But that will be a following work, so +1 for merging this one!

**Comment by dimtruck** [comment]
It's coming next!

**Pull request merged**
