### PR TITLE
add support for CORS and merge-header filters

### PR DESCRIPTION
**Pull request by shintasmith**
This PR adds support for CORS and merge-header Repose filters.

### CODE REVIEW

**Comment by shintasmith** [comment]
For some reasons, the centos kitchen tests failed for me. All the other ubuntu and debian flavors are passing fine.

**Comment by drenalin23** [comment]
Why not a unit test for the CORS filter recipe?

**Comment by shintasmith** [comment]
@drenalin23 , was an oversight, let me add it

**Comment by shintasmith** [comment]
Thanks! Merging this as I need it to make changes in metrics-repose

**Pull request merged**
